version: '2'

services:
  master:
    image: 'bitnami/postgresql:latest'
    container_name: master
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER:-}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD:-}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-}
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=2
  replica1:
    image: 'bitnami/postgresql:latest'
    container_name: replica1
    ports:
      - 5433:5432
    depends_on:
      - master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER:-}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD:-}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-}
  replica2:
    image: 'bitnami/postgresql:latest'
    container_name: replica2
    ports:
      - 5434:5432
    depends_on:
      - master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER:-}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD:-}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-}

volumes:
  postgresql_master_data:
